name: muze
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^0.6.0
  cupertino_icons: ^0.1.2
  auto_route: ^0.2.1
  cached_network_image: ^2.0.0
  shimmer: ^1.0.1
  flutter_svg: ^0.17.1
  device_preview: ^0.2.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator: ^0.2.1+3

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/group.png
    - assets/images/group.svg
    - assets/images/blueThing.png
    - assets/images/discover.svg
    - assets/images/Oval.svg
    - assets/images/greenOval.svg
    - assets/images/pause.svg
  fonts:
    - family: MuzeIcons
      fonts:
        - asset: assets/fonts/MuzeIcons.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.otf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.otf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.otf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.otf
          weight: 700
